# GITHUB: https://github.com/garethcmatthews/docker-lamp
version: "3.8"
networks:
    frontend:
        driver: bridge
        internal: false
    backend:
        driver: bridge
        internal: true
services:
    mysql:
        # DOCKER HUB: https://hub.docker.com/_/mysql/
        build: ./resources/docker/mysql
        container_name: ${COMPOSE_PROJECT_NAME}-mysql
        environment:
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
        healthcheck:
            test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
            timeout: 30s
            interval: 10s
            retries: 10
        command: --default-authentication-plugin=mysql_native_password
        networks:
            - backend
        ports:
            - 3306:3306
    php:
        # DOCKER HUB: https://hub.docker.com/_/php/
        build: ./resources/docker/php
        container_name: ${COMPOSE_PROJECT_NAME}-php
        depends_on:
            mysql:
                condition: service_healthy
        networks:
            - backend
            - frontend
        ports:
            - 8080:80
        volumes:
            - ./:/var/www/html
    phpmyadmin:
        # DOCKER HUB: https://hub.docker.com/_/phpmyadmin
        container_name: ${COMPOSE_PROJECT_NAME}-phpmyadmin
        depends_on:
            mysql:
                condition: service_healthy
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_USER: "root"
            PMA_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
        image: phpmyadmin:5.0.4-apache
        networks:
            - backend
            - frontend
        ports:
            - 8888:80
